name: Testing stuff

on:
  push:
    branches:
      - new_branch

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: skip detection
        if: ${{ contains(env.COMMIT_MESSAGES, '#skip') }}
        run: echo skip detected
